server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: vendas-service
  cloud:
    openfeign:
      micrometer:
        enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vendas_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1994}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:vendas-service},%X{correlationId:-},%X{traceId:-},%X{spanId:-}] "

# Configuração do Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      contratosService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

  retry:
    instances:
      contratosService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,retries,prometheus
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://localhost:4318/v1/traces}
