server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: compras-service
          uri: lb://compras-service
          predicates:
            - Path=/api/compras/**
        - id: contratos-service
          uri: lb://contratos-service
          predicates:
            - Path=/api/contratos/**
        - id: vendas-service
          uri: lb://vendas-service
          predicates:
            - Path=/api/vendas/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:api-gateway},%X{traceId:-},%X{spanId:-}] "

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://localhost:4318/v1/traces}
