{
 "title": "Logs Observability",
 "tags": [
  "logs",
  "loki",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Serviço",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   { "name": "search", "label": "Busca" }
  ]
 },
 "panels": [
  {
   "title": "Volume de Logs por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({compose_project=\"eng-software-devops-unifor-microservices\", service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Volume de Logs por Instância/Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (count_over_time({compose_project=\"eng-software-devops-unifor-microservices\", service=~\"$service\", container=~\"$container\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{compose_project=\"eng-software-devops-unifor-microservices\", service=~\"$service\", container=~\"$container\"} |= \"$search\""
    }
   ]
  }
 ]
}